<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928306206_226084_4088" refElementId="_10_5_622020d_1132928306206_226084_4088"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="PrinterIOException" refElementId="_9_5_f720368_1110473546581_538714_6917" refid="_9_5_f720368_1110473546581_538714_6917"/></annotatedElement><body humanName="Body" mode="s,e">The &lt;code&gt;PrinterIOException&lt;/code&gt; class is a subclass of
{@link PrinterException} and is used to indicate that an IO error
of some sort has occurred while printing.

&lt;p&gt;As of release 1.4, this exception has been retrofitted to conform to
the general purpose exception-chaining mechanism.  The
"&lt;code&gt;IOException&lt;/code&gt; that terminated the print job"
that is provided at construction time and accessed via the
{@link #getIOException()} method is now known as the &lt;i&gt;cause&lt;/i&gt;,
and may be accessed via the {@link Throwable#getCause()} method,
as well as the aforementioned "legacy method."
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="PrinterIOException" refElementId="_9_5_f720368_1110473546581_538714_6917" refid="_9_5_f720368_1110473546581_538714_6917"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="PrinterIOException" refElementId="_9_5_f720368_1110473546581_538714_6917" refid="_9_5_f720368_1110473546581_538714_6917"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>