<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_2051026490.jpg" id="_10_5_622020d_1132928308600_176364_5392"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="ClosedByInterruptException" refid="_9_5_f720368_1110473546643_66645_7881"/></annotatedElement><body humanName="Body" mode="s,e">Checked exception received by a thread when another thread interrupts it
while it is blocked in an I/O operation upon a channel.  Before this
exception is thrown the channel will have been closed and the interrupt
status of the previously-blocked thread will have been set.

@version 1.9, 01/11/19
@since 1.4
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_1555793073.jpg" mode="s,e" name="ClosedByInterruptException" refid="_9_5_f720368_1110473546643_66645_7881"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="ClosedByInterruptException" refid="_9_5_f720368_1110473546643_66645_7881"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>