<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_2051026490.jpg" id="_10_5_622020d_1132928309120_920687_5817"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="CertStoreException" refid="_9_5_f720368_1110473546674_35100_8313"/></annotatedElement><body humanName="Body" mode="s,e">An exception indicating one of a variety of problems retrieving
certificates and CRLs from a &lt;code&gt;CertStore&lt;/code&gt;.
&lt;p&gt;
A &lt;code&gt;CertStoreException&lt;/code&gt; provides support for wrapping
exceptions. The {@link #getCause getCause} method returns the throwable,
if any, that caused this exception to be thrown.
&lt;p&gt;
&lt;b&gt;Concurrent Access&lt;/b&gt;
&lt;p&gt;
Unless otherwise specified, the methods defined in this class are not
thread-safe. Multiple threads that need to access a single
object concurrently should synchronize amongst themselves and
provide the necessary locking. Multiple threads each manipulating
separate objects need not synchronize.

@see CertStore

@version 	1.7 12/19/03
@since	1.4
@author	Sean Mullan
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_1555793073.jpg" mode="s,e" name="CertStoreException" refid="_9_5_f720368_1110473546674_35100_8313"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_1555793073.jpg" name="CertStoreException" refid="_9_5_f720368_1110473546674_35100_8313"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>