<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928309060_547963_5747" refElementId="_10_5_622020d_1132928309060_547963_5747"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="ServerRuntimeException" refElementId="_9_5_f720368_1110473546674_194437_8245" refid="_9_5_f720368_1110473546674_194437_8245"/></annotatedElement><body humanName="Body" mode="s,e">From a server executing on JDK&amp;nbsp;1.1, a
&lt;code&gt;ServerRuntimeException&lt;/code&gt; is thrown as a result of a
remote method invocation when a &lt;code&gt;RuntimeException&lt;/code&gt; is
thrown while processing the invocation on the server, either while
unmarshalling the arguments, executing the remote method itself, or
marshalling the return value.

A &lt;code&gt;ServerRuntimeException&lt;/code&gt; instance contains the original
&lt;code&gt;RuntimeException&lt;/code&gt; that occurred as its cause.

&lt;p&gt;A &lt;code&gt;ServerRuntimeException&lt;/code&gt; is not thrown from servers
executing on the Java 2 platform v1.2 or later versions.

@version 1.18, 05/18/04
@author  Ann Wollrath
@since   JDK1.1
@deprecated no replacement
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="ServerRuntimeException" refElementId="_9_5_f720368_1110473546674_194437_8245" refid="_9_5_f720368_1110473546674_194437_8245"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="ServerRuntimeException" refElementId="_9_5_f720368_1110473546674_194437_8245" refid="_9_5_f720368_1110473546674_194437_8245"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>