<?xml version="1.0" encoding="UTF-8"?><magicdraw><comment classType="Comment" humanType="Comment" icon="index_files/icon_comment_841774062.jpg" id="_10_5_622020d_1132928308910_492858_5588" refElementId="_10_5_622020d_1132928308910_492858_5588"><annotatedElement humanName="Annotated Element" mode="s,e"><class classType="Class" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="ActivateFailedException" refElementId="_9_5_f720368_1110473546674_821738_8125" refid="_9_5_f720368_1110473546674_821738_8125"/></annotatedElement><body humanName="Body" mode="s,e">This exception is thrown by the RMI runtime when activation
fails during a remote call to an activatable object.

@author 	Ann Wollrath
@version	1.10, 12/19/03
@since 	1.2
</body><documentation humanName="Documentation"/><owner classType="Class" humanName="Owner" humanType="Class" icon="index_files/icon_class_555864569.jpg" mode="s,e" name="ActivateFailedException" refElementId="_9_5_f720368_1110473546674_821738_8125" refid="_9_5_f720368_1110473546674_821738_8125"/><owningElement classType="Class" humanName="Owning Element" humanType="Class" icon="index_files/icon_class_555864569.jpg" name="ActivateFailedException" refElementId="_9_5_f720368_1110473546674_821738_8125" refid="_9_5_f720368_1110473546674_821738_8125"/><TO_DO humanName="To Do" mode="s,e"/></comment></magicdraw>